version: "3"

services:
  postgres:
    image: "postgres:11"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    image: "redis:6.2.5-buster"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  app:
    container_name: tweets_backend
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/tweetsbackend
      - app-gems:/app-gems
    # env_file:
    #   - ".env"

volumes:
  redis:
  postgres:
  app-gems:
